= Konto
:imagesdir: _images/
:icons: font

== Benutzerkonto erstellen
Zur Nutzung des agrirouter benötigst du ein Benutzerkonto.

. Öffne die Internetadresse https://goto.my-agrirouter.com/um/register/user[my-agrirouter.com]. + 
=> Das Formular `Benutzerregistrierung` wird angezeigt.
. Fülle die Pflichtfelder aus und klicke den Button *_Registrieren_*. + 
=> Du erhälst eine E-Mail mit dem Aktivierungslink.
. Klicke in der E-Mail den Button *_ACCOUNT AKTIVIEREN_*. + 
=>Das Formular `Benutzerkonto aktivieren` wird angezeigt.
. Vergebe ein Kennwort und klicke den Button *_Sichern_*.

TIP: Das Eingabefeld *_Beschreibung der Firma_* im Formular `Benutzerregistrierung` ist kein Pflichtfeld. Es empfiehlt sich, TODO TEXT einzutragen, denn das Feld wird angezeigt, wenn andere Kunden dich suchen.

== Kontodaten ändern
Du kannst alle bei der Erstellung des Benutzerkontos gemachten Angaben nachträglich ändern.

. Klicke die Kachel *_Kontoverwaltung_*. + 
=> Die `Kontoverwaltung` wird angezeigt.
. Um die Angaben zum Ansprechpartner zu ändern, klicke den Button *_Bearbeiten_* im Abschnitt `Angaben zum Ansprechpartner`. + 
=> Das Formular `Daten Ansprechpartner bearbeiten` wird angezeigt.
. Gebe die neuen Werte ein und klicke auf *_Bestätigen_*.
. Um die Angaben zur Firma zu ändern, klicke den Button *_Bearbeiten_* im Abschnitt `Angaben zur Firma`. + 
=> Das Formular `Daten der Firma bearbeiten` wird angezeigt.
. Gebe die neuen Werte ein und klicke auf *_Bestätigen_*.
. Um deine E-Mail-Adresse zu ändern, klicke den Button *_Email-Adresse ändern_* im Abschnitt `Angaben zum Ansprechpartner`. + 
=> Das Formular `Email-Adresse ändern` wird angezeigt.
. Gebe die E-Mail-Adresse in beide Eingabefelder ein und klicke auf *_Bestätigen_*.
. Klicke auf das Icon *_Startseite_* und kehre in das Dashboard zurück.

== Konto löschen
. Klicke den Button *_Konto löschen_*. + 
=> Ein Meldungsfenster wird angezeigt.
. Klicke den Button *_OK_*. + 
=> Das Konto wird gelöscht.

CAUTION: (oder ähnlich) was alles wird gelöscht? Alle Endpunkte? Welche Daten?

== Einstellungen ändern
Das Erscheinungsbild der Benutzeroberfläche, der Inhalt der Startseite und die Darstellung der Benachrichtigungen können eingestellt werden.

. Klicke auf das Icon *_Profil_*.
. Klicke auf das Icon *_Einstellungen_*. + 
=> Das Fenster `Einstellungen` wird angezegt.
. Nehme alle Änderungen vor und klicke dann den Button *_Sichern_*.

=== Benutzeroberfläche einstellen
Im Reiter `Theme` kannst du zwischen einem dunklen und einem hellen Erstellungsbild wählen.
Im Reiter `Anzeigeeinstellungen` kannst Du die Animationen ausschalten und die Größe der Bedienelemente ändern.

. Klicke den Button *_Erscheinungsbild_*.
. Wähle ein Theme und stelle die Anzeige ein.

=== Startseite einstellen
Du kannst wählen, ob auf dem Dashboard alle Kacheln angezeigt werden, oder nur die Kacheln der jeweils aktiven Gruppe.

Klicke den Button *_Startseite_*.
Wähle die Ansicht des Dashboards.

=== Benachrichtigungen einstellen
Du kannst...

. Klicke den Button *_Benachrichtigungen_*.
. Aktiviere die gewünschten Optionen.
