= Konto
:imagesdir: _images/
:icons: font

== Konto erstellen
Zur Nutzung des agrirouter benötigst du ein Benutzerkonto.

. Öffne die Internetadresse https://goto.my-agrirouter.com/um/register/user[my-agrirouter.com]. + 
=> Das Formular _Benutzerregistrierung_ wird angezeigt.
. Fülle die Pflichtfelder aus und klicke den Button _Registrieren_. + 
=> Du erhälst eine E-Mail mit dem Aktivierungslink.
. Klicke in der E-Mail den Button _ACCOUNT AKTIVIEREN_. + 
=>Das Formular _Benutzerkonto aktivieren_ wird angezeigt.
. Vergebe ein Kennwort und klicke den Button _Sichern_.

TIP: Das Eingabefeld _Beschreibung der Firma_ im Formular _Benutzerregistrierung_ ist kein Pflichtfeld. Es empfiehlt sich, TODO TEXT einzutragen, denn das Feld wird angezeigt, wenn andere Kunden dich suchen.

== Kontodaten ändern
Du kannst alle bei der Registrierung gemachten Angaben nachträglich ändern.

. Klicke die Kachel _Kontoverwaltung_. + 
=> Die _Kontoverwaltung_ wird angezeigt.
. Um die Angaben zum Ansprechpartner zu ändern, klicke den Button _Bearbeiten_ im Abschnitt Angaben zum Ansprechpartner. + 
=> Das Formular _Daten Ansprechpartner bearbeiten_ wird angezeigt.
. Gebe die neuen Werte ein und klicke auf _Bestätigen_.
. Um die Angaben zur Firma zu ändern, klicke den Button _Bearbeiten_ im Abschnitt Angaben zur Firma. + 
=> Das Formular _Daten der Firma bearbeiten_ wird angezeigt.
. Gebe die neuen Werte ein und klicke auf _Bestätigen_.
. Um deine E-Mail-Adresse zu ändern, klicke den Button _Email-Adresse ändern_ im Abschnitt Angaben zum Ansprechpartner. + 
=> Das Formular _Email-Adresse ändern_ wird angezeigt.
. Gebe die E-Mail-Adresse in beide Eingabefelder ein und klicke auf _Bestätigen_.
. Klicke auf das Icon _Startseite_ und kehre in das Dashboard zurück.

== Konto löschen
. Klicke den Button _Konto löschen_. + 
=> Ein Meldungsfenster wird angezeigt.
. Klicke den Button _OK_. + 
=> Das Konto wird gelöscht.

== Einstellungen ändern
Das Erscheinungsbild der Benutzeroberfläche, der Inhalt der Startseite und die Darstellung der Benachrichtigungen können eingestellt werden.

. Klicke auf das Icon _Profil_.
. Klicke auf das Icon _Einstellungen_. + 
=> Das Fenster _Einstellungen_ wird angezegt.
. Nehme alle Änderungen vor und klicke erst dann den Button _Sichern_.

=== Benutzeroberfläche einstellen
Im Reiter _Theme_ kannst du zwischen einem dunklen und einem hellen Erstellungsbild wählen.
Im Reiter _Anzeigeeinstellungen_ kannst Du die Animationen ausschalten und die Größe der Bedienelemente ändern.

. Klicke den Button _Erscheinungsbild_.
. Wähle ein Theme und stelle die Anzeige ein.

=== Startseite einstellen
Du kannst wählen, ob auf dem Dashboard alle Kacheln angezeigt werden, oder nur die Kacheln der jeweils aktiven Gruppe.

Klicke den Button _Startseite_.
Wähle die Ansicht des Dashboards.

=== Benachrichtigungen einstellen
Du kannst...

. Klicke den Button _Benachrichtigungen_.
. Aktiviere die gewünschten Optionen.
