:imagesdir: _images/

= Account pairing

== Account pairing

//Publishing and Subskription erklären
//Maschinen mit live Telemetrie 
//Datenfluss ein / aus
//Externe Maschinen


== ...

Du kannst deinen agrirouter mit Konten anderer Landwirte sowie Lohnunternehmern verbinden und Informationen sowie Daten austauschen. 
Schalte dazu über den entsprechenden Button den Datenfluss ein bzw. aus. Den Datenfluss zwischen zwei verbundenen agrirouter Konten legst du durch Routen (siehe Menüpunkt „Routing“) fest. 
Ein Klick auf die Kachel „Konten verbinden“ zeigt dir alle Verbindungen sowie offene und erhaltene Einladungen. 

Möchtest du eine Verbindung herstellen, brauchst du die E-Mail-Adresse des anderen agrirouter Kontos, mit dem du dich verbinden möchtest. 
Vergib dazu einen frei wählbaren Anzeigennamen. Gib anschließend beides in die entsprechenden Felder ein. In der Rubrik „Offene Einladungen“ siehst du sofort deine Anfrage. 
Möchtest du die Verbindung doch nicht herstellen, kannst du deine Anfrage wieder aufheben.


Dieses Verfahren funktioniert auch umgekehrt. Wenn sich jemand mit dir bzw. deinem agrirouter Konto verbinden möchte, erhältst du eine Einladung per E-Mail. 
Sobald du diese Einladung durch Anklicken öffnest, landest du direkt auf deiner agrirouter Startseite. 
Dort kannst du die Einladung in der Rubrik “Empfangene Einladungen“ ansehen, annehmen oder ablehnen.
