:imagesdir: _images/

= Einführung

== Was ist der agrirouter?
!Review alter Text ...

Wilkommen im agrirouter Benutzerhandbuch! Der agrirouter ist eine universelle Datenaustauschplattform, mit der du deine Maschinen und deine Agrarsoftware herstellerübergreifend verbinden kannst. Um dies zu tun, benötigst du einen agrirouter-Account.

Das agrirouter Benutzerhandbuch wird dir zeigen, wie du einen kostenlosen agrirouter-Account erstellst. Außerdem zeigen wir dir, wie du deinen agrirouter einrichtest und benutzt.

Kapitel 1: xref:basics.adoc[Grundlagen]

Kapitel 2: xref:account.adoc[Konto]

Kapitel 3: xref:endpoint.adoc[Endpunkt]

Kapitel 4: xref:routing.adoc[Route]

Kapitel 5: xref:group.adoc[Gruppe]

Kapitel 6: xref:account-pairing.adoc[Konto verbinden]

Kapitel 7: xref:support.adoc[Service & Support]

Kapitel 8: xref:appendix.adoc[Anhang]


Erklärung für Simbole, Hinweise usw., die verwendet werden:

'NOTE', 'TIP', 'IMPORTANT', 'WARNING', 'CAUTION'

wann werden welche eingesetzt!!!

Wie lese ich diese Kapitel und was bedeuten die Symbole?

[NOTE]
====
.....
====

[TIP]
====
.....
====

[IMPORTANT]
====
.....
====

[WARNING]
====
.....
====

[CAUTION]
====
.....
====
