:imagesdir: _images/

= Einführung

== Was ist der agrirouter?
!Review alter Text ...

Wilkommen im agrirouter Benutzerhandbuch! Der agrirouter ist eine universelle Datenaustauschplattform, mit der du deine Maschinen und deine Agrarsoftware herstellerübergreifend verbinden kannst. Um dies zu tun, benötigst du einen agrirouter-Account.

Das agrirouter Benutzerhandbuch wird dir zeigen, wie du einen kostenlosen agrirouter-Account erstellst. Außerdem zeigen wir dir, wie du deinen agrirouter einrichtest und benutzt.

...

!weitere Punkte als zusammenfassung aller Kapietel!


Kapitel 1 Grundlagen: xref:basics.adoc[Grundlagen]
Kapitel 2 Konto: xref:account.adoc[Konto]
Kapitel 3 Endpunkt: xref:endpoint.adoc[Endpunkt]
Kapitel 4 Route: xref:routing.adoc[Route]
Kapitel 5 Gruppe: xref:group.adoc[Gruppe]
Kapitel 6 Konto verbinden: xref:account-pairing.adoc[Konto verbinden]
Kapitel 7 Service & Support: xref:support.adoc[Service & Support]

Erklärung für:

'NOTE', 'TIP', 'IMPORTANT', 'WARNING', 'CAUTION'

wann werden welche eingesetzt!!!

====
NOTE: .....
====

====
TIP: .....
====

====
IMPORTANT: .....
====

====
WARNING: .....
====

====
CAUTION: .....
====

© 2022 DKE-Data GmbH & Co. KG

* xref:https://my-agrirouter.com/en/footer/privacy-policy[Privacy Policy]
* xref:https://my-agrirouter.com/en/footer/legal-notice[Legal Notice]

Privacy Policy: https://my-agrirouter.com/en/footer/privacy-policy

Legal Notice: https://my-agrirouter.com/en/footer/legal-notice
