:imagesdir: _images/
:icons: font

= Routing

Eine xref:introduction.adoc#route[Route] ist die Verbindung zwischen zwei Endpunkten, d.h. über die Route fließen die Daten vom Sender zum Empfänger.

Das Routing regelt den Datenverkehr auf den Routen.

[IMPORTANT]
====
Der agrirouter transportiert Daten, bearbeitet oder speichert sie aber nicht. + 

Eine Ausnahme bilden Daten, die nicht zugestellt werden können, z.B. weil der Empfänger offline ist. Der agrirouter puffert diese Daten für 4 Wochen. Ist der Empfänger während der gesamten Zeit nicht erreichbar, werden die Daten gelöscht.
====

In diesem Abschnitt erfährst du

* wann und welche Routen automatisch angelegt werden
* an Beispielen, wie du eine Route anlegst


== Automatisch angelegte Routen

Die ein- und abgehenden Routen sowie das Routing der beiden xref:introduction.adoc#standard-gruppen[Standard-Gruppen] werden vom System vorgegeben und können nicht geändert werden.

#TODO#
Sollen/können diese Routen beschrieben werden? Frage ist für jour fixe erfasst.

#TODO#
Diese Routen können nicht bearbeitet werden. Du kannst nur den Gruppen neue Mitglieder hinzufügen oder entfernen.

== Abgehende Routen
Über eine abgehende Route sendest du Daten von einem Endpunkt oder einer Gruppe an einen Empfänger.

* Wie du eine abgehende Route für einen Endpunkt anlegst, bearbeitest und löscht, erfährst du hier...
* Wie du eine abgehende Route für eine Gruppe anlegst, bearbeitest und löscht, erfährst du hier...

== Eingehende Routen
Über eine eingehende Route empfängt der Endpunkt oder die Gruppe Daten von einem Sender.

* Wie du eine eingehende Route für einen Endpunkt anlegst, bearbeitest und löscht, erfährst du hier...
* Wie du eine eingehende Route für eine Gruppe anlegst, bearbeitest und löscht, erfährst du hier...

== Häufig verwendete Routen

=== ...Maschine zu Maschine

=== ...Agrarsoftware zu Agrarsoftware

=== ...Telemetrie-Einheit zu Agrarsoftware

