:imagesdir: _images/
:icons: font

= Routing

Eine xref:introduction.adoc#route[Route] ist die Verbindung zwischen zwei Endpunkten, d.h. über die Route fließen die Daten vom Sender zum Empfänger.
[.result]#Mit der Route legst du fest, wer Nachrichten austauscht.#

Das Routing regelt den Datenverkehr auf den Routen.
[.result]#Mit dem Routing legst du fest, welche Nachrichten ausgetauscht werden.#

[IMPORTANT]
====
Erstelle eingehende und/oder abgehende Routen für jeden Endpunkt, jede Gruppe und jedes verbundene Konto.
Ohne Route kein Datenaustausch.
====

[NOTE]
====
Der agrirouter transportiert Daten, bearbeitet oder speichert sie aber nicht. + 

Eine Ausnahme bilden Daten, die nicht zugestellt werden können, z.B. weil der Empfänger offline ist. Der agrirouter puffert diese Daten für 4 Wochen. Ist der Empfänger während der gesamten Zeit nicht erreichbar, werden die Daten gelöscht.
====

In diesem Abschnitt erfährst du

* wann und welche Routen automatisch angelegt werden
* an Beispielen, wie du eine Route anlegst


== Automatisch angelegte Routen

Die eingehenden und abgehenden Routen der beiden xref:introduction.adoc#standard-gruppen[Standard-Gruppen] werden vom System vorgegeben und können nicht geändert werden:

* Mitglieder der Agrarsoftware-Gruppe senden alle Daten, d.h. alle Nachrichten und Echtzeitdaten, an alle Mitglieder der Maschinen-Gruppe
* Mitglieder der Maschinen-Gruppe senden alle Daten, d.h. alle Nachrichten und Echtzeitdaten, an alle Mitglieder der Agrarsoftware-Gruppe

== Abgehende Routen
Über eine abgehende Route sendest du Daten von einem Endpunkt oder einer Gruppe an einen Empfänger.

* Wie du eine abgehende Route für einen Endpunkt anlegst, bearbeitest und löscht, erfährst du xref:endpoint.adoc#senden-an[hier...]
* Wie du eine abgehende Route für eine Gruppe anlegst, bearbeitest und löscht, erfährst du xref:group.adoc#senden-an[hier...]

== Eingehende Routen
Über eine eingehende Route empfängt der Endpunkt oder die Gruppe Daten von einem Sender.

* Wie du eine eingehende Route für einen Endpunkt anlegst, bearbeitest und löscht, erfährst du xref:endpoint.adoc#empfangen-von[hier...]
* Wie du eine eingehende Route für eine Gruppe anlegst, bearbeitest und löscht, erfährst du xref:group.adoc#empfangen-von[hier...]

