:imagesdir: _images/
:icons: font

= Anhang A, DDIs

Viele Maschinen können während der Feldarbeit Maschinen-, Positions- und Prozessparameter in Echtzeit versenden.

Es gibt über 600 solcher Parameter, z.B. 

* Soll- und Istwerte in den Auftragsdaten
* Spritverbrauch, Geschwindigkeit oder Tankfüllung in den Maschinendaten

Wir haben die Parameter zur besseren Übersicht in 12 Kategorien zusammengefasst.
Wie in den Abschnitten xref:endpoint.adoc#detail-view[Endpunkt] bzw. xref:group.adoc#detail-view[Gruppe] beschrieben, wählst du bei der Erstellung von Routen eine oder mehrere Kategorien aus.
[.result]#Alle der gewählten Kategorie zugeordneten Parameter können dann zwischen den Endpunkten ausgetauscht werden.#

[NOTE]
====
Die Maschinen-, Positions- und Prozessparameter sind in der ISOBUS-Norm ISO 11783 definiert und heißen dort DDI (Data Dictionary Identifier). + 
Die DDIs sind im https://www.isobus.net/isobus/dDEntity[ISOBUS Data Dictionary^] veröffentlicht.
====

Es folgt eine Liste aller Kategorien und der ihnen zugeordneten Parameter:

== GPS Positionsdaten und Guidance-Informationen

GPS Positionsdaten (Nord- und Ost-Koordinaten), an der die Telemetriedaten gemessen oder protokolliert wurden.
Daten mit Bezug zu geografischen und Guidance.Informationen.

include::partial$ddis/position.adoc[]

== Allgemeine Prozessdaten
Auftrags- und Lebensdauerzähler oder Durchschnittswerte (Zähler, die für Ausbringung und/oder Ertrag nicht relevant sind).

include::partial$ddis/general.adoc[]

== Kraftstoff und Harnstofflösung

Daten mit Bezug zum Verbrauch von Kraftstoff und Harnstofflösung von Maschinen (Gesamtenergieverbrauch).

include::partial$ddis/fuel.adoc[]

== Maschineneigenschaften

Nicht prozessrelevante Daten zu den Maschineneigenschaften.

include::partial$ddis/machine.adoc[]

== Ausbringung

Daten über die Ausbringung auf dem Feld (z.B. Düngemittel, Saatgut, Pflanzenschutzmittel, Trockenmasse, usw.).

include::partial$ddis/application.adoc[]


== Ertragsdaten

Menge und Eigenschaften des Erntegutes

include::partial$ddis/yield.adoc[]

== Prozessdaten

Daten über den Hauptarbeitsprozess der Maschine.

include::partial$ddis/process.adoc[]

== Umgebungsbedingungen

Daten mit Bezug zu den Umgebungsbedingungen (z.B. Windgeschwindigkeit).

include::partial$ddis/environment.adoc[]

== Basisdaten

Grundlegende Werte, die für das gesamte System relevant sind.

include::partial$ddis/basic.adoc[]

== Maschinendaten (nur PGN)

Maschinendaten, die zur PGN (Parameter Group Number) gehören; z.B. Hubwerksposition, Zapfwellendrehzahl, etc.

include::partial$ddis/pgn.adoc[]

== Proprietäre Daten

Herstellerspezifische Daten (nicht Bestandteil des Standards).

include::partial$ddis/proprietary.adoc[]

== Bodendaten

Bedingungen und Sensordaten zur Bodenbeschaffenheit.

include::partial$ddis/soil.adoc[]
